services:
  app:
    build: .
    env_file: .env
    ports:
      - "8081:8081"

  mongodb:
    image: mongo
    volumes:
      - datadb:/data/db
    ports:
      - "27017:27017"

    
volumes:
  datadb:
